### ISSUE TITLE
Mouseless not working on Firefox interneral pages 

### ISSUE THREAD

**Issue by joereddington** [mortie/mouseless-plugin#14]
Mouseless isn't triggering on pages internal to firefox - is that a known issue? 

Examples: 
* The ad-on manager 
* The LastPass preferences page
* Mouseless's page on the mozillia site: https://addons.mozilla.org/en-GB/firefox/addon/mouseless-plugin/ 

any ideas?

**Comment by mortie** [comment]
Mozilla doesn't let any add-on modify internal pages or addons.mozilla.com (for good reasons - imagine an add-on which made itself impossible to uninstall by breaking the add-on manager), and mouseless works by injecting some javascript into pages. There's sadly not really anything I can do about it.

**Comment by joereddington** [comment]
Sounds like a pretty good reason.  Shame really. Workarounds appreciated, but will close issue
