### ISSUE TITLE
Disable shortcuts for some URL patterns

### ISSUE THREAD

**Issue by dedeibel** [mortie/mouseless-plugin#2]
Hi¹,

I would like to see the possibility to enable or disable the plugin using a URL filter.

I often have the problem that I use one site (bitbucket pull-requests) which makes heavy use of shortcuts. I like the default settings of the plugin and the site…

An alternative could be to add a configurable shortcut to disable the plugin (like with the button in the Firefox bar)

Submitted via plugin

_¹) awesome plugin, used mouseless browsing addon before but then it stopped working and thought about trying the alternative. Like it since it is way simpler and faster providing most features I need._

**Comment by mortie** [comment]
I'm glad you like the add-on :)

Adding a blacklist is a good idea. I can add a textbox to the options page where you can write a bunch of regexes (separated by a newline), and if the URL matches any of those regexes, the add-on is disabled for that tab. That way, you could write a regex like `https://bitbucket.org/.*/pull-requests/`, and the add-on would be disabled on bitbucket's pull request pages. Does that sound like a good solution?

**Comment by mortie** [comment]
I just pushed a commit which adds the blacklist feature: https://github.com/mortie/mouseless-plugin/commit/160aca6f9007ddb096742c016aeaeff6b7e92d4f

The update is submitted to Mozilla, and should be live within the next few days. Once it is, just go into the add-on's preferences, and enter `https://bitbucket.org/.*/pull-requests/` in the text field called `Blacklisted URLs`.

**Comment by dedeibel** [comment]
Thanks sound excellent and will try it on the spot. It will be javascript style regex I suppose.
